_BASE_: "Base-RCNN-FPN-BN.yaml"
MODEL:
  MASK_ON: True
  WEIGHTS: "See Instructions"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]  
  RESNETS:
    STRIDE_IN_1X1: False
    DEPTH: 50  
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
  FORMAT: "RGB"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  BASE_LR: 0.02
OUTPUT_DIR: "./coco_R50_FPN_mopro"     